lib/yamato_web/router.ex
defmodule YamatoWeb.Router do
  use YamatoWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", YamatoWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/about", PageController, :about)
    get("/blog", PageController, :blog)
    get("/admin", PageController, :admin)

    resources "/articles", ArticleController do
      resources("/comments", CommentController, only: [:create, :delete])
    end

    resources("/notes", NoteController)
    resources("/images", ImageController)
    resources("/stories", StoryController)

    get("/auth/register", UserController, :new)
    post("/auth/register", UserController, :create)
    get("/auth/login", SessionController, :new)
    post("/auth/login", SessionController, :create)
    delete("/auth/logout", SessionController, :delete)
  end

  # Other scopes may use custom stacks.
  # scope "/api", YamatoWeb do
  #   pipe_through :api
  # end
end

lib/yamato_web/templates/page/about.html.eex
<h2>About</h2>

lib/yamato_web/templates/page/admin.html.eex
<div class="columns">
  <div class="column is-one-quarter">
    <div class="menu">
      <p class="menu-label">Erstellen</p>
      <ul class="menu-list">
        <li><%= link "Neue Geschichte", to: story_path(@conn, :new) %></li>
        <li><%= link "Neuer Artikel", to: article_path(@conn, :new) %></li>
        <li><%= link "Neue Notiz", to: note_path(@conn, :new) %></li>
        <li><%= link "Neues Bild", to: image_path(@conn, :new) %></li>
      </ul>
      <p class="menu-label">Account</p>
      <ul class="menu-list">
        <li><%= link "Ausloggen", to: session_path(@conn, :delete), method: :delete, class: "navbar-item"  %></li>
      </ul>
    </div>
  </div>
  <div class="column">
    <h3 class="title">Geschichten</h3>

    <%= for article <- @articles do %>
      <li><%= link article.title, to: article_path(@conn, :show, article) %></li>
    <% end %>

    <%= for note <- @notes do %>
      <li> <%= note.content %> </li>
    <% end %>

    <%= for story <- @stories do %>
      <li><%= link story.name, to: story_path(@conn, :show, story) %></li>
    <% end %>
  </div>
</div>

lib/yamato_web/templates/page/blog.html.eex
<div class="hero has-text-centered is-medium">
  <div class="hero-body">
    <h2 class="title glitch-light" data-text="Technos & Psyche">Technos & Psyche</h2>
  </div>
</div>

<div class="columns">
  <div class="column">
    <h3 class="subtitle">Artikel</h3>

    <ul>
      <%= for article <- @articles do %>
      <li>
        <%= link article.title, to: article_path(@conn, :show, article) %>
      </li>
      <% end %>
    </ul>

    <div style="margin-top: 1rem;">
      <%= link "mehr..", to: article_path(@conn, :index), class: "button is-small is-outlined is-primary" %>
    </div>
  </div>
  <div class="column">
    <h3 class="subtitle">Geschichten</h3>
  </div>
  <div class="column">
    <h3 class="subtitle">Notizen</h3>
  </div>
</div>

lib/yamato_web/templates/page/index.html.eex
<section class="hero is-large front-page">
  <div class="hero-body">
    <div class="container">
      <h1 class="title glitch-dark" data-text="I think perfection is ugly. Somewhere in the things humans make, I want to see scars, failure, disorder, distortion.">
        I think perfection is ugly. Somewhere in the things humans make, I want to see scars, failure, disorder, distortion.
      </h1>
      <h2 class="subtitle">
        ― Yohji Yamamoto
      </h2>
    </div>
  </div>
</section>