lib/yamato_web/router.ex
defmodule YamatoWeb.Router do
  use YamatoWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", YamatoWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/about", PageController, :about)
    get("/blog", PageController, :blog)
    get("/admin", PageController, :admin)

    resources "/articles", ArticleController do
      resources("/comments", CommentController, only: [:create, :delete])
    end

    resources("/notes", NoteController)
    resources("/images", ImageController)
    resources("/stories", StoryController)

    get("/auth/register", UserController, :new)
    post("/auth/register", UserController, :create)
    get("/auth/login", SessionController, :new)
    post("/auth/login", SessionController, :create)
    delete("/auth/logout", SessionController, :delete)
  end

  # Other scopes may use custom stacks.
  # scope "/api", YamatoWeb do
  #   pipe_through :api
  # end
end

lib/yamato/blog/article.ex
defmodule Yamato.Blog.Article do
  use Ecto.Schema
  import Ecto.Changeset
  alias Yamato.Helpers.Tags

  schema "articles" do
    field(:title, :string)
    field(:content, :string)
    field(:excerpt, :string)
    field(:tags, {:array, :string})
    field(:tags_string, :string, virtual: true, default: "")
    field(:draft, :boolean)
    has_many(:comments, Yamato.Blog.Comment)

    timestamps()
  end

  @doc false
  def changeset(article, attrs) do
    article
    |> cast(attrs, [:title, :content, :excerpt, :tags_string, :draft])
    |> validate_required([:title, :content])
    |> Tags.convert_tags_string_to_list()
  end
end

lib/yamato_web/controllers/article_controller.ex
defmodule YamatoWeb.ArticleController do
  use YamatoWeb, :controller

  alias Yamato.Blog
  alias Yamato.Blog.{Article, Comment}

  plug(YamatoWeb.Plugs.CheckAuth when action in [:new, :create, :edit, :update, :delete])

  def index(conn, _params) do
    articles =
      case get_session(conn, :current_user_id) do
        nil -> Blog.list_published_articles()
        _ -> Blog.list_articles()
      end

    render(conn, "index.html", articles: articles)
  end

  def new(conn, _params) do
    changeset = Blog.change_article(%Article{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"article" => article_params}) do
    case Blog.create_article(article_params) do
      {:ok, article} ->
        conn
        |> put_flash(:info, "Article created successfully.")
        |> redirect(to: article_path(conn, :show, article))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> render("new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    article = Blog.get_article!(id)
    comment_changeset = Comment.changeset(%Comment{})
    render(conn, "show.html", article: article, comment_changeset: comment_changeset)
  end

  def edit(conn, %{"id" => id}) do
    article = Blog.get_article!(id)
    changeset = Blog.change_article(article)
    render(conn, "edit.html", article: article, changeset: changeset)
  end

  def update(conn, %{"id" => id, "article" => article_params}) do
    article = Blog.get_article!(id)

    case Blog.update_article(article, article_params) do
      {:ok, article} ->
        conn
        |> put_flash(:info, "Article updated successfully.")
        |> redirect(to: article_path(conn, :show, article))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", article: article, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    article = Blog.get_article!(id)
    {:ok, _article} = Blog.delete_article(article)

    conn
    |> put_flash(:info, "Article deleted successfully.")
    |> redirect(to: article_path(conn, :index))
  end
end

lib/yamato_web/controllers/blog/article_controller.ex
defmodule YamatoWeb.Blog.ArticleController do
  use YamatoWeb, :controller

  alias Yamato.Blog
  alias Yamato.Blog.{Article, Comment}

  plug(YamatoWeb.Plugs.CheckAuth when action in [:new, :create, :edit, :update, :delete])

  def index(conn, _params) do
    articles =
      case get_session(conn, :current_user_id) do
        nil -> Blog.list_published_articles()
        _ -> Blog.list_articles()
      end

    render(conn, "index.html", articles: articles)
  end

  def new(conn, _params) do
    changeset = Blog.change_article(%Article{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"article" => article_params}) do
    case Blog.create_article(article_params) do
      {:ok, article} ->
        conn
        |> put_flash(:info, "Article created successfully.")
        |> redirect(to: article_path(conn, :show, article))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> render("new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    article = Blog.get_article!(id)
    comment_changeset = Comment.changeset(%Comment{})
    render(conn, "show.html", article: article, comment_changeset: comment_changeset)
  end

  def edit(conn, %{"id" => id}) do
    article = Blog.get_article!(id)
    changeset = Blog.change_article(article)
    render(conn, "edit.html", article: article, changeset: changeset)
  end

  def update(conn, %{"id" => id, "article" => article_params}) do
    article = Blog.get_article!(id)

    case Blog.update_article(article, article_params) do
      {:ok, article} ->
        conn
        |> put_flash(:info, "Article updated successfully.")
        |> redirect(to: article_path(conn, :show, article))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", article: article, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    article = Blog.get_article!(id)
    {:ok, _article} = Blog.delete_article(article)

    conn
    |> put_flash(:info, "Article deleted successfully.")
    |> redirect(to: article_path(conn, :index))
  end
end

lib/yamato_web/views/article_view.ex
defmodule YamatoWeb.ArticleView do
  use YamatoWeb, :view

  def markdown(body) when is_nil(body), do: "No content!"

  def markdown(body) do
    body
    |> Earmark.as_html!()
    |> raw
  end

  def date_format(date) do
    Timex.format!(date, "{D}. {Mshort} {YYYY}")
  end

  def tags_string(tags) when is_nil(tags), do: ""
  def tags_string(tags), do: Enum.join(tags, ",")
end

lib/yamato_web/views/blog/article_view.ex
defmodule YamatoWeb.Blog.ArticleView do
  use YamatoWeb, :view

  def markdown(body) when is_nil(body), do: "No content!"

  def markdown(body) do
    body
    |> Earmark.as_html!()
    |> raw
  end

  def date_format(date) do
    Timex.format!(date, "{D}. {Mshort} {YYYY}")
  end

  def tags_string(tags) when is_nil(tags), do: ""
  def tags_string(tags), do: Enum.join(tags, ",")
end

lib/yamato_web/templates/article/edit.html.eex
<%= render "form.html", Map.put(assigns, :action, article_path(@conn, :update, @article)) %>

lib/yamato_web/templates/article/form.html.eex
<%= form_for @changeset, @action, [class: "article-form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="notification is-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <div class="control">
      <%= text_input f, :title, class: "input is-size-3", placeholder: "The Title" %>
      <%= error_tag f, :title %>
    </div>
  </div>

  <div class="columns meta">
    <div class="column">
      <div class="field">
        <%= label f, :draft, "Meta", class: "label" %>
        <div class="control">
          <label class="checkbox">
            <%= checkbox f, :draft, class: "checkbox" %>
            Is Draft?
          </label>
          <%= error_tag f, :draft %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= text_input f, :tags_string, class: "input", type: "tags", value: tags_string(@changeset.data.tags) %>
          <%= error_tag f, :tags_string %>
        </div>
      </div>
    </div>
    <div class="column">
      <div class="field">
        <%= label f, :excerpt, "Excerpt", class: "label" %>
        <div class="control">
          <%= textarea f, :excerpt, class: "textarea", spellcheck: true %>
          <%= error_tag f, :excerpt %>
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= textarea f, :content, class: "textarea", id: "editor" %>
      <%= error_tag f, :content %>
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= submit "Save & Show", class: "button is-primary" %>
    </div>
  </div>
<% end %>

<style media="screen">
  .CodeMirror {
    height: 400px;
    border: 1px solid #bbb;
  }
</style>
<script src="<%= static_path(@conn, "/admin/easymde.min.js") %>"></script>
<script src="<%= static_path(@conn, "/admin/bulma-tagsinput.min.js") %>"></script>
<script>
  const easymde = new EasyMDE({
    autoDownloadFontAwesome: false,
    element: document.getElementById("editor"),
    spellChecker: false,
    placeholder: "Spread your knowledge.."
  })
</script>

lib/yamato_web/templates/article/index.html.eex
<%= for article <- @articles do %>
  <div class="columns">
    <div class="column is-half">
      <section class="hero">
        <div class="hero-body">
            <h1 class="title">
              <%= link article.title, to: article_path(@conn, :show, article), class: "btn btn-default btn-xs" %>
            </h1>
            <h2 class="subtitle has-text-grey">
              <%= date_format(article.inserted_at) %>
            </h2>
            <%= render_shared "tags.html", tags: article.tags, small: true %>
        </div>
      </section>
    </div>

    <div class="column">

      <section class="hero">
        <div class="hero-body">
          <div class="content">
            <%= markdown(article.excerpt) %>
          </div>
        </div>
      </section>
    </div>
  </div>
<% end %>

<%= if signed_in?(@conn) do %>
  <p>
    <%= link "New Article", to: article_path(@conn, :new), class: "button is-primary" %>
  </p>
<% end %>

lib/yamato_web/templates/article/new.html.eex
<%= render "form.html", Map.put(assigns, :action, article_path(@conn, :create)) %>

lib/yamato_web/templates/article/show.html.eex
<article class="post article">
  <section class="hero is-medium">
    <div class="hero-body">
      <div class="container has-text-centered">
        <h1 class="title">
          <%= @article.title %>
        </h1>
        <h2 class="subtitle has-text-grey">
          <%= date_format(@article.inserted_at) %>
        </h2>

        <%= render_shared "tags.html", tags: @article.tags, small: false %>
      </div>
    </div>
  </section>

  <div class="content">
    <%= markdown(@article.content) %>
  </div>

  <div class="comment-form">
    <%= render YamatoWeb.CommentView, "new.html", conn: @conn, article: @article, comment_changeset: @comment_changeset %>
  </div>

  <div class="comments">
    <ul>
      <%= for comment <- @article.comments do %>
        <article class="media">
          <figure class="media-left">
            <p class="image is-64x64">
              <img src="https://bulma.io/images/placeholders/128x128.png">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong><%= comment.author %></strong> <small>@johnsmith</small> <small>31m</small>
                <br />
                <%= comment.content %>
              </p>
            </div>
            <nav class="level is-mobile">
              <div class="level-left">
                <a class="level-item">
                  <span class="icon is-small"><i class="fas fa-reply"></i></span>
                </a>
                <a class="level-item">
                  <span class="icon is-small"><i class="fas fa-retweet"></i></span>
                </a>
                <a class="level-item">
                  <span class="icon is-small"><i class="fas fa-heart"></i></span>
                </a>
              </div>
            </nav>
          </div>
          <%= if signed_in?(@conn) do %>
          <div class="media-right">
            <%= link "", to: article_comment_path(@conn, :delete, @article.id, comment.id), method: :delete, data: [confirm: "Are you sure?"], class: "delete" %>
          </div>
          <% end %>
        </article>
      <% end %>
    </ul>
  </div>
</article>

<%= if signed_in?(@conn) do %>
  <p>
    <span><%= link "Edit", to: article_path(@conn, :edit, @article), class: "button is-primary" %></span>
    <span><%= link "Delete", to: article_path(@conn, :delete, @article), method: :delete, data: [confirm: "Are you sure?"], class: "button is-danger" %></span>
  </p>
<% end %>